import Head from 'next/head'
import Image from 'next/image';
import { Inter } from 'next/font/google'
import Banner from '@/components/Banner/Banner';
import styles from '@/components/Home/style.module.scss';
import classNames from 'classnames/bind';
import Section from '@/components/Section/Section';
import Bnimg from '@/public/banner/bn.jpg';
import ListCourse from '@/components/Home/ListCourse';
import Intro1 from '@/components/Intro/Intro1';
import MostView from '@/components/Home/MostView';
import TopCategories from '@/components/Home/TopCategories';
import Intro2 from '@/components/Intro/Intro2';
import Team from '@/components/Intro/Team';
import { ListIntro } from '@/public/data';

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Metalearn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Section>
        <Banner img={Bnimg} title='Học trực tuyến một cách tiện lợi và hiệu quả nhất !' text='Bắt đầu tham gia ngay hôm nay để nâng cao kiến thức và kỹ năng của bạn.'/>
        <ListCourse/>
        </Section>
        <Intro1/>
        <Section>
          <MostView/>
          <TopCategories/>
          <Intro2 data={ListIntro[0]}/>
        </Section>
        <Team/>
        <Section>
        <Intro2 data={ListIntro[1]} rev/>
        <Intro2 data={ListIntro[2]} />
        </Section>
  
      </main>
    </>
  )
}
